jhipster-dev-postgresql:
  container_name: SoundUp-dev-postgresql
  image: postgres:9.4.5
  # volumes:
  # - ~/volumes/jhipster/SoundUp/dev-postgresql/:/var/lib/postgresql/
  environment:
  - POSTGRES_USER=SoundUp
  - POSTGRES_PASSWORD=
  ports:
  - "5432:5432"

